YAK-1757/Adding secrets support
flipkart-incubator/hbase-k8s-operator pull request #27
Opened 2024-02-21 13:01 UTC by saifahmed-2

2024-03-05 15:20 UTC, rda3mon requested changes

2024-03-05 15:20 UTC, rda3mon commented on helm-charts/hbase-chart/templates/_secret.tpl
> +  name: {{ .Values.secrets.configs.name }}
secrets.configs? why such a structure?

2024-03-05 15:20 UTC, rda3mon commented on helm-charts/hbase-chart/templates/_secret.tpl
> +    kubernetes.io/service-account.name: {{ .Values.secrets.configs.tokenServiceAccount }}
what is this?

2024-03-05 15:20 UTC, rda3mon commented on helm-charts/hbase-chart/templates/_secret.tpl
> +  {{ .Values.secrets.configs.key }}: {{ .Values.secrets.configs.value }}
structure doesn't look fine.

2024-03-11 07:36 UTC, saifahmed-2 commented on helm-charts/hbase-chart/templates/_secret.tpl
> +  name: {{ .Values.secrets.configs.name }}
Have corrected structure and pushed.

2024-03-11 07:37 UTC, saifahmed-2 commented on helm-charts/hbase-chart/templates/_secret.tpl
> +    kubernetes.io/service-account.name: {{ .Values.secrets.configs.tokenServiceAccount }}
service-account.name is the sa you get while describing namspace.

2024-03-11 07:37 UTC, saifahmed-2 commented on helm-charts/hbase-chart/templates/_secret.tpl
> +  {{ .Values.secrets.configs.key }}: {{ .Values.secrets.configs.value }}
Fixed

2024-03-11 09:59 UTC, diptam-in submitted a review, later dismissed
LG

2024-03-12 08:38 UTC, rda3mon commented on operator/controllers/utils.go
> +			volume = corev1.Volume{
spaces are not consistent

2024-03-12 08:42 UTC, rda3mon commented on helm-charts/hbase-chart/templates/_secret.tpl
> +      kubernetes.io/service-account.name: {{ .tokenServiceAccount }}
why will this service token be different from `{{ .Values.serviceAccountName }}`

2024-03-12 08:43 UTC, rda3mon commented on helm-charts/hbase-chart/templates/_secret.tpl
> +  namespace: {{ .namespace }}
why is this not same as `: {{ .Values.namespace }}`

2024-03-12 10:46 UTC, saifahmed-2 commented on helm-charts/hbase-chart/templates/_secret.tpl
> +      kubernetes.io/service-account.name: {{ .tokenServiceAccount }}
it can be same also (you can have default , .Values.serviceAccountName or any other  sa associated with your namespace)

2024-03-12 10:46 UTC, saifahmed-2 commented on helm-charts/hbase-chart/templates/_secret.tpl
> +  namespace: {{ .namespace }}
this is same only. Since range function is used in secret.tpl hence have to mention in manifest

2024-03-12 10:47 UTC, saifahmed-2 commented on operator/controllers/utils.go
> +			volume = corev1.Volume{
it is similar as other (configmap, hostpath)

2024-03-12 13:58 UTC, saifahmed-2 commented on helm-charts/hbase-chart/templates/_secret.tpl
> +      kubernetes.io/service-account.name: {{ .tokenServiceAccount }}
why will this service token be different from {{ .Values.serviceAccountName }} --> updated

2024-03-12 13:59 UTC, saifahmed-2 commented on helm-charts/hbase-chart/templates/_secret.tpl
> +  namespace: {{ .namespace }}
why is this not same as : {{ .Values.namespace }} --> updated accordingly

2024-03-12 16:21 UTC, merged